# Generated by Django 4.1 on 2022-10-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_volunteer_table_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='donate_items_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20, null=True)),
                ('item_type', models.CharField(max_length=20, null=True)),
                ('item_image', models.FileField(null=True, upload_to='')),
                ('item_desc', models.CharField(max_length=12, null=True)),
                ('donor_username', models.FileField(max_length=12, null=True, upload_to='')),
                ('volunteer_username', models.FileField(max_length=12, null=True, upload_to='')),
            ],
        ),
    ]
