# Generated by Django 4.1 on 2022-10-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_donate_items_details_item_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate_items_details',
            name='donor_username',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='donate_items_details',
            name='volunteer_username',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
