# Generated by Django 4.1 on 2022-10-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_donate_items_details_donor_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate_items_details',
            name='item_image',
            field=models.ImageField(upload_to='donate_items_images'),
        ),
    ]
