# Generated by Django 4.1 on 2022-10-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_donate_items_details_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate_items_details',
            name='item_image',
            field=models.ImageField(null=True, upload_to='donate_items_images'),
        ),
    ]
