# Generated by Django 4.1 on 2022-11-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_donate_items_details_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate_items_details',
            name='donor_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donate_items_details',
            name='donor_mobile_no',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='donate_items_details',
            name='volunteer_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donate_items_details',
            name='volunteer_mobile_no',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
