# Generated by Django 4.1 on 2022-11-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_donate_items_details_donor_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor_table',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='iimages'),
        ),
    ]
